name: Pytest Automation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/test_token_checker.py'
      - 'scripts/test_line_mapper.py'

permissions:
  contents: read

jobs:
  pytest-automation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install pipenv
      run: |
        pip install pipenv
    - name: Install dependencies
      run: |
        pipenv install

    - name: Install pytest
      run: |
        pipenv run pip install pytest
        
    - name: Run pytest token checker
      working-directory: scripts
      run: | 
        pipenv run pytest test_token_checker.py
        
    - name: Run pytest line mapper
      working-directory: scripts
      run: | 
        pipenv run pytest test_line_mapper.py